steps:
 # build the container
 - name: 'gcr.io/cloud-builders/docker'
   args: ['build', '--network=cloudbuild','-t','gcr.io/'${PROJECT_ID}'/nuxtapp', '.']
 # push to container registry
 - name: 'gcr.io/cloud-builders/docker'
   args: ['push', 'gcr.io/'${PROJECT_ID}'/nuxtapp']
 # deploy container to cloud run
 - name: 'gcr.io/cloud-builders/gcloud'
   args: ['run', 'deploy','nuxtapp', '--image', 'gcr.io/'${PROJECT_ID}'/nuxtapp', '--region', 'europe-west2', '--platform', 'managed', '--allow-unauthenticated']
images:
 - 'gcr.io/'${PROJECT_ID}'/nuxtapp'