steps:
 # build the container
 - name: 'gcr.io/cloud-builders/docker'
   args: ['build', '-t','gcr.io/${PROJECT_ID}/${_SERVICE_NAME}-${_PR_NUMBER}-${SHORT_SHA}', '.']
 # push to container registry
 - name: 'gcr.io/cloud-builders/docker'
   args: ['push', 'gcr.io/${PROJECT_ID}/${_SERVICE_NAME}-${_PR_NUMBER}-${SHORT_SHA}']
 # deploy container to cloud run with tag
 - name: 'gcr.io/cloud-builders/gcloud'
   args: ['run', 'deploy','${_SERVICE_NAME}', '--platform', 'managed', '--region', '${_REGION}', '--image', 'gcr.io/${PROJECT_ID}/${_SERVICE_NAME}-${_PR_NUMBER}-${SHORT_SHA}','--tag', 'pr-${_PR_NUMBER}', '--no-traffic']
 # Link revisions on pull request
 - name: 'gcr.io/${PROJECT_ID}/deployment-previews'
   secretEnv: ["GITHUB_TOKEN"]
   args: ['set', '--project-id', '${PROJECT_ID}', '--region', '${_REGION}','--service', '${_SERVICE_NAME}', '--pull-request', '${_PR_NUMBER}', '--repo-name', '${_GITHUB_REPO}', '--commit-sha', '${SHORT_SHA}']
substitutions:
  _SERVICE_NAME: previewService
  _REGION: europe-west2
  _GITHUB_REPO: $REPO_NAME
options:
  dynamicSubstitutions: true
availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/github_token/versions/latest
      env: 'GITHUB_TOKEN'
images:
 - 'gcr.io/${PROJECT_ID}/nuxtapp'